### ISSUE TITLE
Error when reproduce the result  :  No OpKernel was registered to support Op 'CudnnRNNParamsSize' 

### ISSUE THREAD

**Issue by eryueniaobp** [Arturus/kaggle-web-traffic#13]
any tips to solve the error? 
 
python 3.6 + tensorflow 1.4.1     

GPU :  Nvidia  Tesla M40

**Comment by Nickkontscha** [comment]
I had the same issue. I fixed it by uninstalling tensorflow and then installating tensorflow-gpu==1.4.0

**Comment by Arturus** [comment]
Fixed by last commit
