### ISSUE TITLE
Is there a version which can train the model by CPU?

### ISSUE THREAD

**Issue by waldstein1983** [Arturus/kaggle-web-traffic#16]
Unfortunately, I currently do not have GPU support

**Comment by Arturus** [comment]
Unfortunately no, because this code depends on CUDA RNN libraries for training.
But you can replace tensorflow.contrib.cudnn_rnn.CudnnGRU in a model.py to CPU-friendly variant, such as GRUCell + tf.nn.dynamic_rnn. It should be easy enough.
