### ISSUE TITLE
SMAC3 parameter tuning code

### ISSUE THREAD

**Issue by wasd12345** [Arturus/kaggle-web-traffic#19]
In hparams.py, there are many parameter sets which can be used. Running the train.py script using the command suggested in the readme uses the parameter set s32, or it is easy to input my own parameters and run with those instead.

But can you also provide the script you used for running SMAC3 on your models for tuning? I know you said the different parameter sets did not have too much difference in performance but would be interested to use this SMAC step as well.

Thanks

**Comment by Arturus** [comment]
You can look here: https://gist.github.com/Arturus/c32b186f9b964a7007a786daec6ca310
