### ISSUE TITLE
Question about .params_size() in model.py

### ISSUE THREAD

**Issue by H0bbitBaron** [Arturus/kaggle-web-traffic#24]
Hello @Arturus ! Firstly thank you for sharing your code and congratulations with the first place)

I'm digging code and stuck on this few lines - https://github.com/Arturus/kaggle-web-traffic/blob/master/model.py#L72

Can you please clarify what is params_size? As stated in TF [docs](https://www.tensorflow.org/versions/r1.3/api_docs/python/tf/contrib/cudnn_rnn/CudnnGRU#params_size) it returns "size of the opaque parameter buffer". The hell is this - hyperparameter size/memory limit/batch size that can fit into my particular GPU memory?

And leading question - why do we need to [check](https://github.com/Arturus/kaggle-web-traffic/blob/master/model.py#L75) the values of the two returns of the one same function [build_rnn](https://github.com/Arturus/kaggle-web-traffic/blob/master/model.py#L66)?

Thank you in advance!

**Comment by amirkhango** [comment]
Good question. I am also curious. Have you done it?

**Comment by Arturus** [comment]
Model is fixed to work with TF 1.10, params_size magic is redundant for modern Tensorflow and was removed.
