### ISSUE TITLE
 make_features.py

### ISSUE THREAD

**Issue by Vaisili** [Arturus/kaggle-web-traffic#29]
Dear Arturus:
I just run "python make_features.py data/vars --add_days=63"  but come cross that error:

  File "make_features.py", line 310, in run
    dow_norm = features_days.dayofweek.values / week_period
AttributeError: 'numpy.ndarray' object has no attribute 'values'

How can i solve it?

**Comment by meerahshivn** [comment]
Hi, have you able to resolve this error?
