### ISSUE TITLE
ImportError: cannot import name 'Collection'

### ISSUE THREAD

**Issue by moonlit77** [Arturus/kaggle-web-traffic#3]
When i ran : python make_features.py data/vars --add_days=63 ,got  an error:

Traceback (most recent call last):
  File "make_features.py", line 10, in <module>
    from typing import Tuple, Dict, Collection, List
ImportError: cannot import name 'Collection'

I am using python 3.5 .

**Comment by Arturus** [comment]
I use Python 3.6, try this version
