### ISSUE TITLE
which python version do you use?

### ISSUE THREAD

**Issue by yuyingg0921** [Arturus/kaggle-web-traffic#4]
"from typing import Collection"
I use python 2.7 and 3.5 to run your code.
Because this will result an error, I would like to know which version of python did you use?
python 3.6?
thanks.

**Comment by Arturus** [comment]
Yes, Python 3.6
You can safely remove all Collection references from the code, this is just syntax sugar for IDE

**Comment by yuyingg0921** [comment]
thx!!! I used 3.6 and it works!
and may I ask that do you have the answer of this kaggle competition?
I am not sure if kaggle will release the true result after this competition is end or not?
thank you very much.
