### ISSUE TITLE
the training data is lost

### ISSUE THREAD

**Issue by sladesha** [Arturus/kaggle-web-traffic#5]
I can't get the training data from the url:https://www.kaggle.com/c/web-traffic-time-series-forecasting/data, and it seems to be '404'. So could u please upload them?  thx.

**Comment by Arturus** [comment]
https://www.kaggle.com/c/web-traffic-time-series-forecasting/data is web page address, you should log into Kaggle interface and download train_2.csv from interface.

Direct link is https://www.kaggle.com/c/web-traffic-time-series-forecasting/download/train_2.csv.zip
