### ISSUE TITLE
 answer of this kaggle competition

### ISSUE THREAD

**Issue by yuyingg0921** [Arturus/kaggle-web-traffic#6]
may I ask that do you have the answer of this kaggle competition?
I am not sure if kaggle will release the true result after this competition is end or not?
thank you very much.

**Comment by Arturus** [comment]
I don't have an answer, but it can be downloaded from Wikipedia (pageviews data for all pages are publicly accesible)

**Comment by yuyingg0921** [comment]
okay, thank you:)
