### ISSUE TITLE
 Cannot colocate nodes `m_2/global_norm/L2Loss` and `m_2/gradients/m_2/CudnnRNN_grad/CudnnRNNBackprop` 

### ISSUE THREAD

**Issue by sparo-jack** [Arturus/kaggle-web-traffic#8]
>windows10

>tensorflow1.4

Cannot colocate nodes `m_2/global_norm/L2Loss` and `m_2/gradients/m_2/CudnnRNN_grad/CudnnRNNBackprop` because no device type supports both of those nodes and the other nodes colocated with them

> Colocation Debug Info:
> 
> Colocation group had the following types and devices: 
> 
> CudnnRNNBackprop: GPU
> 
> Identity: 
> 
> L2Loss: CPU

	 [[Node: m_2/global_norm/L2Loss = L2Loss[T=DT_FLOAT, _class=["loc:@m_2/gradients/m_2/CudnnRNN_grad/CudnnRNNBackprop"], _device="/device:GPU:0"](m_2/gradients/m_2/CudnnRNN_grad/tuple/control_dependency_3)]]

**Comment by Arturus** [comment]
CuDNN did'nt work properly on Windows.

**Comment by 59ranjbar** [comment]
Hi Art,
First, thanks for this incredible job.
I have the same issue as Sparo-jack had. Could you please let me know how we can resolve this issue!
I have tensorflow-gpu==1.10.0 on my machine.
Appreciate it in advance.
